### ISSUE TITLE
First Name

### ISSUE THREAD

**Issue by Gmfholley** [GETConfOmaha/splash_page#4]
https://github.com/GETConfOmaha/splash_page/blob/fd209337599c0417b69f1e659a506791c0f5667a/index.html#L87

Could we change this to either both first name and last name or just name?

(My preference is just a single input for name, as it is the easiest for accessibility, but if mailchimp needs both, then add both).

**Comment by JenHomann** [comment]
@kaseymccormick as you've been integrating with MailChimp, I'd like to assign this out to you. We can discuss more in our call tomorrow.

**Comment by kaseymccormick** [comment]
It becomes a data thing, what if a person has a hypen in last name or two last names. They do first and last name but I only chose first name as I think we'll only really want to address them by first name.

**Comment by JenHomann** [comment]
@Gmfholley In our discussion last night, Kasey and I agreed with the following solution: we will add first name and last name fields, but keep them optional. The only data we *need* is email, but having first and last name will help us be slightly more sophisticated in monitoring/tracking/targeting.

**Comment by kaseymccormick** [comment]
taken care of
