### ISSUE TITLE
Wording suggestion - first para

### ISSUE THREAD

**Issue by Gmfholley** [GETConfOmaha/splash_page#5]
https://github.com/GETConfOmaha/splash_page/blob/fd209337599c0417b69f1e659a506791c0f5667a/index.html#L37

> GETConf - short for Gender Equity in Tech Conference - is a one-day conference by women, for everyone. It is a tech conference at its core with the mission to amplify and celebrate the voices of women and non-men, and educate and connect female, male, and non-binary attendees.

Suggestion to change this to:

> GETConf (Gender Equity in Tech Conference) is a one-day tech conference by women, for everyone.  Our mission is to amplify and celebrate the voices of women and non-men, and educate and connect the tech community.

Reasons: 
- No passive voice
- shorten
- make tech more prominent

**Comment by JenHomann** [comment]
Thanks for the suggestions, @Gmfholley. I like a lot of this. At this point, the last line of this paragraph is the only place where we call out that this isn't just a women's conference.  Would you be comfortable with keeping in "female, male and non-binary attendees" as opposed to "the tech community"?

**Comment by Gmfholley** [comment]
We use the word 'everyone' in the first sentence, but yes, that might be a good thing to remain. I generally try to avoid the adjective form of these words and use nouns instead: 'women, men, and non-binaries'.

I was also a little concerned about whether these three terms together includes everyone.  I will try to find out, but I think this is a fine change for now.

I think we should make a FAQ soon, because I imagine the number one questions will be who is it for and who can speak.

**Comment by kaseymccormick** [comment]
I like people of all genders.

**Comment by JenHomann** [comment]
Resolved in PR #10
