### ISSUE TITLE
Suggested wording change - second para

### ISSUE THREAD

**Issue by Gmfholley** [GETConfOmaha/splash_page#6]
https://github.com/GETConfOmaha/splash_page/blob/fd209337599c0417b69f1e659a506791c0f5667a/index.html#L39

> In short, GETConf is a day for anyone in tech to learn from both technical and non-technical thought leaders. And, when all is said and done, it is a day that will strengthen connections across the greater community.

Suggest to change above to:

> GETConf is a day for anyone in tech to learn from both technical and non-technical thought leaders.  We aim to strengthen and build the greater tech community.

Reasons: 
- shorten
- remove clauses
- active voice, personalize

**Comment by JenHomann** [comment]
Suggested changes made and merged in PR #9
