### ISSUE TITLE
Wording change: submit a talk

### ISSUE THREAD

**Issue by Gmfholley** [GETConfOmaha/splash_page#7]
https://github.com/GETConfOmaha/splash_page/blob/fd209337599c0417b69f1e659a506791c0f5667a/index.html#L48

> Are you loving a particular scripting language or framework and want to show off its prowess?

Suggest a change to:

> Do you love a language, library, or framework and want to share why?

Reasons:
- Echo 'Do you' structure of the rest of the list
- Shorter.  I generally think the pithier, the better CTAs (Calls to Action) are.
- Not sure if a language has prowess? I think of prowess as something a thinking being has.
- I am worried about the 'show it off' part putting of women who think they might not be expert enough.  So I changed it to 'share' which I think more women may see themselves in.  (I _do_ want people who will show off their work. But think they will submit anyway.)

-------------------------------

> Do you have learnings to share from your perspective as a DBA, Product Manager, Scrum Master, BA, DevOps, etc.?

Suggest a change to:

> Do you have lessons to share about big data, database administration, networking, DevOps, or cybersecurity?

Reasons:
- Learnings is less usual a noun than lessons
- Add like categories here - the network, the data, and the systems that protect them

--------------------
> Are you a business leader or a member of an HR, legal, marketing, or sales team in tech?

Suggest a change to:

> Do you have stories to tell about product development, project management, or design and UI/UX?

Reasons:
- Although we might accept a talk on legal issues in tech, this is not the focus of tech and not our major audience.  Keep calling out the fields that are tech adjacent that we think are still a core part of our audience.

----------------------

> Are you the only ___ in the room? Are you an entrepreneur? Have you had an experience in tech that you believe would benefit others to learn from?

Suggest change to:

> Are you the only ___ in the room? Are you an entrepreneur? Have you had an experience in tech others could learn from?

Reasons:
- Shorter.
- Note: I love this one. ❤️

**Comment by JenHomann** [comment]
Changes made and merged in via: https://github.com/GETConfOmaha/splash_page/pull/8
